# ==============================================================================
# CONFIGURAÇÃO DO GOOGLE APP ENGINE
# ==============================================================================
# Este arquivo configura o deploy da aplicação Spring Boot no App Engine.
#
# Deploy: gcloud app deploy

runtime: java17
instance_class: F2

env_variables:
  # Configurações de Banco de Dados (Cloud SQL)
  # Substitua pelos valores do seu projeto
  DB_USER: "feedbackuser"
  DB_PASSWORD: "your-secure-password"
  INSTANCE_CONNECTION_NAME: "your-project:us-central1:feedbackdb"

  # URLs das Cloud Functions
  NOTIFICATION_FUNCTION_URL: "https://us-central1-your-project.cloudfunctions.net/notifyAdmin"
  REPORT_FUNCTION_URL: "https://us-central1-your-project.cloudfunctions.net/generateReport"

  # Configurações JWT
  JWT_SECRET: "sua-chave-secreta-jwt-super-segura-256-bits-minimo"
  JWT_EXPIRATION: "86400000"

# Configurações de recursos
automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.65

# Health check
health_check:
  enable_health_check: true
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

# Handlers
handlers:
  - url: /.*
    script: auto
    secure: always
