# ==============================================================================
# GOOGLE CLOUD BUILD - CI/CD AUTOMÁTICO
# ==============================================================================
# Este arquivo configura o build e deploy automatizado via Cloud Build.
#
# Trigger: git push para branch main

steps:
  # Step 1: Build da aplicação Spring Boot com Maven
  - name: 'maven:3.9-eclipse-temurin-17'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']
    id: 'build-spring-boot'

  # Step 2: Deploy no App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']
    id: 'deploy-app-engine'
    waitFor: ['build-spring-boot']

  # Step 3: Deploy da Cloud Function de Notificação
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'notifyAdmin'
      - '--runtime=nodejs20'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--entry-point=notifyUrgentFeedback'
      - '--source=cloud-functions/notification-function'
      - '--region=us-central1'
    id: 'deploy-notification-function'

  # Step 4: Deploy da Cloud Function de Relatório
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'generateReport'
      - '--runtime=nodejs20'
      - '--trigger-topic=weekly-report'
      - '--entry-point=generateWeeklyReport'
      - '--source=cloud-functions/report-function'
      - '--region=us-central1'
    id: 'deploy-report-function'

# Timeout total do build
timeout: '1800s'

# Logs
options:
  logging: CLOUD_LOGGING_ONLY
